title: Image

accept:
  extension: jpg, jpeg, png, mp3, mp4, ics, mov, pdf, zip, svg, webp

columns:
  main:
    width: 1/1
    sections:
      meta:
        type: fields
        fields:
          alt:
            label: Alternative Text
            type: text
            required: true
          photographer:
            label: Photogapher
            type: text
            width: 1/2
            default: Laura Gauch