title: Datasecurity Page

columns:
  main:
    width: 2/3
    sections:
    # DATASECURITY
      bio:
        type: fields
        fields:
          datasecurity:
            label: Data Security
            type: writer
            marks: 
              - link
            nodes: false