title: Default Page

# columns:
#   main:
#     width: 2/3
#     sections:
#       fields:
#         type: fields
#         fields:
#           text:
#             type: textarea
#             size: huge
#   sidebar:
#     width: 1/3
#     sections:
#       pages:
#         type: pages
#         template: default
#       files:
#         type: files

fields:
  info:
    label: Info
    type: info
    text: |
      Hi! <3 Go back, there is nothing to do here (:

options:
  list: 
    admin: true
    editor: false