title: Project
# preset: page

status:
  draft: Draft
  listed: Published
  unlisted: Privately Published
tabs:
  content:
    label: Content
    icon: text
    columns:
      main:
        width: 2/3
        sections:

        # ???
          details:
            type: fields
            fields:
              description:
                label: Description
                type: writer
                marks: 
                  - link
                nodes: false

              line:
                type: line

              additionalInfo:
                label: Details
                type: structure
                columns:
                  additionalDetails:
                    width: 1/3
                  value:
                    width: 2/3
                  date:
                    width: 1/6
                  dateUntil:
                    width: 1/6
                  
                fields:
                  additionalDetails:
                    label: Add-Ons
                    type: select
                    width: 1/2
                    options:
                      support: Support of
                      collaboration: Collaboration with
                      links: Links
                      nextViewings: Next Viewings
                  value:
                    width: 1/2
                    label: Value
                    type: writer
                    marks:
                      - link
                    nodes: 
                      - bulletList
                  gap:
                    type: gap
                    width: 1/2      
                  date:
                    type: date
                    label: From
                    type: date
                    width: 1/4
                    display: YYYY-MM-DD
                    when:
                      additionalDetails: nextViewings
                  # gapB:
                  #   type: gap
                  #   width: 1/2 
                  dateUntil:
                    type: date
                    label: Until
                    type: date
                    width: 1/4
                    display: YYYY-MM-DD
                    when:
                      additionalDetails: nextViewings

          # PRESSKITS
              presskits:
                type: structure
                label: Presskits
                columns:
                  title:
                    width: 2/6
                  link:
                    width: 3/6
                  toggle:
                    width: 1/6
                fields:
                  toggle:
                    label: Visible
                    type: toggle
                    width: 1/4
                    text: 
                      - "No"
                      - "Yes"
                    default: true                
                  title:
                    label: Name
                    type: text
                    width: 3/4

                  lineA2:
                    type: line

                  target:
                    label: Open in new window?
                    type: toggle
                    text: 
                      - "No"
                      - "Yes"
                    width: 1/4
                    default: true
                  link:
                    label: link
                    type: link
                    options: 
                      - url
                      - file
                      - page
                      - email
                    width: 3/4
  

      sidebar:
        width: 1/3
        sticky: true
        sections:
          color:
            type: fields
            fields:
              backgroundColor:
                label: Background Color
                width: 1/2
                type: color
                alpha: false
                format: hsl
                mode: picker
                required: true
          images:
            type: fields
            fields:
              gallery:
                type: files
                label: Gallery
                sortable: true
                query: site.images
                uploads:
                  parent: site
              vimeo:
                type: text



  seo: seo/page
