title: Project
# preset: page

status:
  draft: Draft
  listed: Published
  unlisted: Privately Published
tabs:
  content:
    label: Content
    icon: text
    columns:
      main:
        width: 2/3
        sections:
          details:
            type: fields
            fields:
              description:
                label: Description
                type: writer
                marks: 
                  - link
                nodes: false

              line:
                type: line

          # SUPPORT
              supportOf:
                type: structure
                label: Support of
                columns:
                  name:
                    width: 5/6
                  toggle:
                    width: 1/6
                fields:                  
                  toggle:
                    label: Visible
                    type: toggle
                    width: 1/5
                    text: 
                      - "No"
                      - "Yes"
                    default: true                
                  name:
                    label: Name
                    type: writer
                    width: 5/6
                    nodes: false
                    marks: 
                      - link

          # COLLABORATION
              collaboration:
                type: structure
                label: In Collaboration with
                columns:
                  name:
                    width: 5/6
                  toggle:
                    width: 1/6
                fields:                  
                  toggle:
                    label: Visible
                    type: toggle
                    width: 1/6
                    text: 
                      - "No"
                      - "Yes"
                    default: true                
                  name:
                    label: Who
                    width: 5/6
                    type: writer
                    nodes: false
                    marks: 
                      - link

          # PRESSKITS
              presskits:
                type: structure
                label: Presskits
                columns:
                  title:
                    width: 5/6
                  toggle:
                    width: 1/6
                fields:
                  toggle:
                    label: Visible
                    type: toggle
                    width: 1/6
                    text: 
                      - "No"
                      - "Yes"
                    default: true                
                  title:
                    label: Name
                    width: 5/6
                    type: writer
                    nodes: false
                    marks: 
                      - link
  
          # NEXT VIEWINGS
              nextViewings:
                type: structure
                label: Next Viewings
                columns:
                  name:
                    width: 3/6
                  date:
                    width: 1/6
                  dateUntil:
                    width: 1/6
                  toggle:
                    width: 1/6
                fields:
                  toggle:
                    label: Visible
                    type: toggle
                    width: 1/6
                    text: 
                      - "No"
                      - "Yes"
                    default: true                
                  name:
                    label: Where
                    type: writer
                    width: 5/6
                    nodes: false
                    marks: 
                      - link
                  lineA2:
                    type: line  
                  date:
                    type: date
                    label: From
                    type: date
                    width: 1/2
                    display: MMMM, DD YYYY
                  dateUntil:
                    type: date
                    label: Until
                    type: date
                    width: 1/2
                    display: MMMM, DD YYYY

      sidebar:
        width: 1/3
        sticky: true
        sections:
          madeWhen:
            type: fields
            fields:
              year:
                label: Year
                type: text
          color:
            type: fields
            fields:
              backgroundColor:
                label: Background Color
                width: 1/2
                type: color
                alpha: false
                format: hsl
                mode: picker
                required: true
          images:
            type: fields
            fields:
              gallery:
                type: files
                label: Gallery
                sortable: true
                query: site.images
                required: true
                uploads:
                  parent: site
              vimeo:
                type: text



  seo: seo/page
