title: Laura Gauch

tabs:
#tab1 PAGES
  pages:
    icon: text
    sections:
      pages:
        type: pages
        status: published


# #tab2 INFO
#   Info:
#     icon: pin
#     columns:
#       main:
#         width: 1/2
#         sections:
         
#       sidebar:
#         width: 1/2
#         sections:
#           contact:
#             type: fields
#             fields:
#               email:
#                 label: General Email
#                 type: email
#               phone:
#                 label: General Phonennumber
#                 type: tel
#               instagram:
#                 label: Instagram Handle
#                 type: url
#               linkedin:
#                 label: LinkedIn Handle
#                 type: url

  media:
    icon: images
    sections:
      gallery:
        type: files
        label: Gallery
        layout: list
        limit: 100
        info: 
          - "{{ file.dimensions }}"
        image:
          cover: true
          ratio: 1/1


  seotab: seo